name: Update submodules in parent repositories

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Update submodules in AWS terraform repository
        env:
          COMMIT_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        run: |
          git clone --recurse-submodules https://florianluediger:$COMMIT_TOKEN@github.com/florianluediger/openbalena-terraform-aws.git
          
          cd openbalena-terraform-aws
          git config user.name "Florian Lüdiger"
          git config user.email "florian.luediger@googlemail.com"
          
          git submodule update --remote
          git add .
          git status
          git commit -m "Update Ansible Playbook submodule"
          
          git push
      - name: Update submodules in Azure terraform repository
        env:
          COMMIT_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        run: |
          git clone --recurse-submodules https://florianluediger:$COMMIT_TOKEN@github.com/florianluediger/openbalena-terraform-azure.git
          
          cd openbalena-terraform-azure
          git config user.name "Florian Lüdiger"
          git config user.email "florian.luediger@googlemail.com"
          
          git submodule update --remote
          git add .
          git status
          git commit -m "Update Ansible Playbook submodule"
          
          git push
